version: "3.7"
services:
  postgres:
    container_name: postgres_container
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: challenge_db
    volumes:
      - ./pgsql/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
  web:
      build: .
      restart: always
      depends_on:
        - postgres
      ports:
        - "8090:8090"
      volumes:
        - ./src:/go/pkg/mod